app: cd
service: deploy
namespace: beta
version: v1
replicas: 1
serviceAccount: false
command:
  - test
  - "1234"
args:
  - "1"
  - "2"
  - "3"
image:
  path: test
  tag: latest
ports:
  - port: 8000
    targetPort: 8000
    name: http
  - port: 9000
    targetPort: 9000
    name: grpc
metrics:
  scrape: true
#  path: /metrics
#  port: 8000
importEnvNames:
  - stage
  - other
configData:
  name: deploy-config
  path: workdir/config
  data:
    config1.yaml: |
      dafjlkdjaskfjdklasjfkldasj
      asdfkasjdfklajsd
      asdfasdfa
workloadType: statefulset
